###################################################################################
### Web服务器配置
###################################################################################
server:
  port: 18081
  servlet:
    context-path: /

###################################################################################
### logging(logback)
###################################################################################
logging:
  config: classpath:logback.xml
  level:
    org.springframework: warn
    org.springframework.jdbc.datasource.DataSourceTransactionManager: debug
    org.springframework.beans.factory: warn
    com.zaxxer.hikari: info
    org.apache.ibatis: info
    org.hibernate.validator: warn
    springfox.documentation: warn
    schemacrawler: error
    us.fatehi: error
    org.clever: debug
    org.clever.hinny.api.require: warn

###################################################################################
### Spring配置
###################################################################################
spring:
  profiles.active: dev
  application.name: graaljs-test
  aop.proxy-target-class: true

  servlet: #------------------------------------------------------------ 文件上传配置
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: 'data/temp'

  http: #------------------------------------------------------------------ http配置
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      force: false

  jackson: #------------------------------------------------------------ jackson配置
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8

  resources: #------------------------------------------------ html、js、css 静态资源
    chain:
      cache: false
      compressed: true
    cache:
      period: 0s
    static-locations: [ 'classpath:/static/' ]

  datasource: #----------------------------------------------------------- 数据库配置
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.40:3306/clever-template
    #url: jdbc:mysql://mysql.msvc.top:3306/clever-template
    username: clever-template
    password: lizhiwei1993
    hikari:
      pool-name: defaultDataSource
      data-source-properties:
        serverTimezone: GMT+8
        useUnicode: true
        characterEncoding: utf-8
        zeroDateTimeBehavior: convert_to_null
        useSSL: false
        useCursorFetch: true
      auto-commit: false
      maximum-pool-size: 1
      minimum-idle: 1
      max-lifetime: 1800000
      connection-test-query: SELECT 1

###################################################################################
### clever
###################################################################################
clever:
  hinny:
    file-system-type: filesystem
    script-path: 'server-ts'
    script-file-watcher:
      include:
        - '*.js'
        - '*.json'
      exclude:
        - '*\node_modules\*'
      enable-watcher: true
      interval: 3s
      delay-millis: 300ms
    engine-instance-pool:
      max-wait-millis: 1000
      min-idle: 1
      max-idle: 1
      max-total: 1
    mvc-handler:
      support-suffix:
        - ''
        - '.json'
        - '.action'
      prefix-mappings:
        - request-path: '/!/'
          script-path: '/dist'
    mybatis-mapper-config:
      mapper-path: 'server-ts/src'
      #mapper-path: 'classpath:server-ts/src/**/*.xml'
      enable-watcher: true
      interval: 1s
      include: [ '*.xml' ]
    multiple-jdbc:
      disable: false
      default-name: default
      global-config:
        driver-class-name: com.mysql.cj.jdbc.Driver
        data-source-properties:
          serverTimezone: GMT+8
          useUnicode: true
          characterEncoding: utf-8
          zeroDateTimeBehavior: convert_to_null
          useSSL: false
          useCursorFetch: true
        auto-commit: false
        maximum-pool-size: 100
        minimum-idle: 5
        max-lifetime: 1800000
        connection-test-query: SELECT 1
      jdbc-map:
        default:
          jdbc-url: jdbc:mysql://192.168.31.40:3306/clever-template
          #jdbc-url: jdbc:mysql://mysql.msvc.top:3306/clever-template
          username: clever-template
          password: lizhiwei1993
    multiple-redis:
      disable: false
      default-name: default
      global-config:
        database: 0
        port: 6379
        lettuce:
          pool:
            max-active: 16
            max-idle: 8
            min-idle: 1
      redis-map:
        default:
          host: redis5.msvc.top
          password: lizhiwei1993
