###################################################################################
### Web服务器配置
###################################################################################
server:
  port: 18081
  servlet:
    context-path: /

###################################################################################
### logging(logback)
###################################################################################
logging:
  config: classpath:logback.xml
  level:
    org.springframework: warn
    org.springframework.jdbc.datasource.DataSourceTransactionManager: debug
    org.springframework.beans.factory: warn
    com.zaxxer.hikari: info
    org.apache.ibatis: info
    org.hibernate.validator: warn
    springfox.documentation: warn
    org.clever: debug
    org.clever.hinny.api.require: warn

###################################################################################
### Spring配置
###################################################################################
spring:
  profiles.active: dev
  application.name: graaljs-test
  aop.proxy-target-class: true

  servlet: #------------------------------------------------------------ 文件上传配置
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: 'data/temp'

  http: #------------------------------------------------------------------ http配置
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      force: false

  jackson: #------------------------------------------------------------ jackson配置
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8

  resources: #------------------------------------------------ html、js、css 静态资源
    chain:
      cache: false
      compressed: true
    cache:
      period: 0s
    static-locations: [ 'classpath:/static/' ]

  datasource: #----------------------------------------------------------- 数据库配置
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.40:3306/clever-template
    username: clever-template
    password: lizhiwei1993
    hikari:
      pool-name: defaultDataSource
      data-source-properties:
        serverTimezone: GMT+8
        useUnicode: true
        characterEncoding: utf-8
        zeroDateTimeBehavior: convert_to_null
        useSSL: false
        useCursorFetch: true
      auto-commit: false
      maximum-pool-size: 100
      minimum-idle: 5
      max-lifetime: 1800000
      connection-test-query: SELECT 1

###################################################################################
### clever
###################################################################################
clever:
  hinny:
    script-path: 'server-ts'
    script-file-watcher:
      enable-watcher: false
      interval: 3s
      delay-millis: 300ms
      include:
        - '*.js'
        - '*.json'
      exclude:
        - '*\node_modules\*'
    engine-instance-pool:
      max-wait-millis: -1
      min-idle: 2
      max-idle: 8
      max-total: 8
    mvc-handler:
      support-suffix:
        - ''
        - '.json'
        - '.action'
      prefix-mappings:
        - request-path: '/!/'
          script-path: '/dist'
    mybatis-mapper-config:
      enable-watcher: true
      mapper-path: 'server-ts/src'
      interval: 1s
      include: [ '*.xml' ]
